Algoritmo "Entrada e Saída de dados"

// Descrição   : Entrada e Saída de dados
// Autor(a)    : Lucas Lima
// Data atual  : 20/02/2024
Var
// Seção de Declarações das variáveis 
   nome: caractere
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite o seu nome:")
   leia(nome)
   escreval("Digite a sua idade:")
   leia(nota)
   
   escreval("o nome digitado foi:", nome)
   escreval("a idade digitada foi:", nota)

Fimalgoritmo