Algoritmo "Operadores Relacionais"
// Discilplina : [Linhuagem e Lógica de Programação]
// Descrição   : Operadores Relacionais!
// Autor(a)    : Lucas Oliveira de Lima
// Data atual  : 23/02/2024
Var
// Seção de Declarações das variáveis
   nota01, nota02: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota01 := 10
   nota02 := 15

   se(nota01 = nota02) então
     escreval("nota01 é diferente"
   senao
      escreval("nota01 é igual")
   fimse
Fimalgoritmo